package View;

import Controller.AccionesBajaClientes;
import Main.FrameMain;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author alvar
 */
public class BajaClientes extends javax.swing.JPanel {

    private FrameMain frame;
    private AccionesBajaClientes acciones;
 
    /**
     * Creates new form BajaClientes
     * @param frame
     */
    public BajaClientes(FrameMain frame) {
        this.frame=frame;
        initComponents();
        acciones=new AccionesBajaClientes(this);
        acciones.refreshTable();
        
    }
     
    public JTable getTable(){
        return ListCli;
    }
    
    public JScrollPane getScrPanel(){
        return jScrollPane1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BorrarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListCli = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        BorrarCliente.setText("Borrar");
        BorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarClienteActionPerformed(evt);
            }
        });

        ListCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Apellido2"
            }
        ));
        ListCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListCliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListCli);

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1goBack(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BorrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BorrarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarClienteActionPerformed
        acciones.eraseClient();
    }//GEN-LAST:event_BorrarClienteActionPerformed

    private void ListCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListCliMouseClicked
        acciones.getTableId();
    }//GEN-LAST:event_ListCliMouseClicked

    private void jButton1goBack(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1goBack

    }//GEN-LAST:event_jButton1goBack


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorrarCliente;
    private javax.swing.JTable ListCli;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
