/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ProductsController;
import Main.FrameMain;
import java.awt.HeadlessException;
import java.awt.TextField;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author alvar
 */
public class PanelProducts extends javax.swing.JPanel {
    
        private FrameMain frame;
        private ProductsController controller;

    /**
     * Creates new form Productos
     */
    public PanelProducts(FrameMain frame) {
        this.frame=frame;
        initComponents();
        controller = new ProductsController(this);
        controller.refreshTable();
    }

    public JTable getTable() {
        return productsList;
    }
    
    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public TextField getTextField_price() {
        return textField_price;
    }

    public TextField getTextfield_name() {
        return textfield_name;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        productsList = new javax.swing.JTable();
        button_addProduct = new javax.swing.JButton();
        button_editProduct = new javax.swing.JButton();
        button_deleteProduct = new javax.swing.JButton();
        textfield_name = new java.awt.TextField();
        textField_price = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("Productos");

        productsList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        productsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(productsList);

        button_addProduct.setText("Añadir Producto");
        button_addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductAction(evt);
            }
        });

        button_editProduct.setText("Editar Producto");
        button_editProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProductAction(evt);
            }
        });

        button_deleteProduct.setText("Borrar Producto");
        button_deleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductAction(evt);
            }
        });

        jLabel2.setText("Nombre");

        jLabel3.setText("Precio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(210, 210, 210))))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(button_addProduct)
                .addGap(18, 18, 18)
                .addComponent(button_editProduct)
                .addGap(18, 18, 18)
                .addComponent(button_deleteProduct)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField_price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfield_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textField_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_addProduct)
                    .addComponent(button_editProduct)
                    .addComponent(button_deleteProduct))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void productsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsListMouseClicked
        controller.writeSelectedRow();
    }//GEN-LAST:event_productsListMouseClicked

    private void addProductAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductAction
        try {
            controller.addProduct();
            JOptionPane.showMessageDialog(this, "Producto añadido.");
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(
                    this, "No se ha podido añadir el producto.");
        }
    }//GEN-LAST:event_addProductAction

    private void editProductAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProductAction
        
        if(getTable().getSelectedRowCount()==1){

                controller.editProduct();
                JOptionPane.showMessageDialog(this, "Producto editado.");
                //JOptionPane.showMessageDialog(this, "No se ha podido editar el producto.");           

        }else{
            if (getTable().getRowCount()==0){
                JOptionPane.showMessageDialog(this, "La tabla esta vacia.");
            } else{
              JOptionPane.showMessageDialog(this,
                      "Por favor, seleccione una fila a modificar.");
            }
        }
    }//GEN-LAST:event_editProductAction

    private void deleteProductAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductAction
        if(getTable().getSelectedRowCount()==1){
            try{
                controller.deleteProduct();
                JOptionPane.showMessageDialog(this, "Producto borrado.");
            }catch(Exception e){
                JOptionPane.showMessageDialog(
                        this, "No se ha podido borrar el producto.");
            }
        }else{
            if (getTable().getRowCount()==0){
                JOptionPane.showMessageDialog(this, "La tabla está vacia.");
            } else{
              JOptionPane.showMessageDialog(
                      this, "Por favor, seleccione un producto que eliminar.");
            }
        }
    }//GEN-LAST:event_deleteProductAction


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_addProduct;
    private javax.swing.JButton button_deleteProduct;
    private javax.swing.JButton button_editProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable productsList;
    private java.awt.TextField textField_price;
    private java.awt.TextField textfield_name;
    // End of variables declaration//GEN-END:variables


}
