/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.SellingsController;
import Main.FrameMain;
import java.awt.Choice;
import java.awt.TextField;
import java.text.DecimalFormat;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author alvar
 */
public class PanelNewSell extends javax.swing.JPanel {
    
        private FrameMain frame;
        private SellingsController controller;
    /**
     * Creates new form PanelVenta
     */
    public PanelNewSell(FrameMain frame) {
        this.frame=frame;
        initComponents();
        controller=new SellingsController(this);
        controller.refreshTable();
        controller.refreshChoicer();
    }

    public JTable getProductsTable() {
        return productsList;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public Choice getChoice_user() {
        return choice_user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        productsList = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        button_buy = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        choice_user = new java.awt.Choice();

        productsList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        productsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsListMouseClicked(evt);
            }
        });
        productsList.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                productsListPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(productsList);

        jLabel2.setText("Confirmar compra");

        button_buy.setText("Aceptar");
        button_buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_buy(evt);
            }
        });

        jLabel3.setText("Comprador");

        jLabel4.setText("Introduzca un número en cantidad* para seleccionar un producto.");

        choice_user.setMaximumSize(new java.awt.Dimension(300, 40));
        choice_user.setMinimumSize(new java.awt.Dimension(150, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(choice_user, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_buy)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap())))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(choice_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(button_buy, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(193, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void productsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsListMouseClicked
        //controller.writeSelectedRow();
    }//GEN-LAST:event_productsListMouseClicked

    private void productsListPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_productsListPropertyChange
        //textField_totalPrice.setText(String.valueOf(controller.calculateTotalPrice()));
    }//GEN-LAST:event_productsListPropertyChange

    private void confirm_buy(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_buy
        controller.newBuy();
    }//GEN-LAST:event_confirm_buy


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_buy;
    private java.awt.Choice choice_user;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable productsList;
    // End of variables declaration//GEN-END:variables
}
