/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.HistoryController;
import Main.FrameMain;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author alvar
 */
public class PanelHistory extends javax.swing.JPanel {
    
        private FrameMain frame;
        private HistoryController controller;

    /**
     * Creates new form PanelHistorial
     */
    public PanelHistory(FrameMain frame) {
        this.frame=frame;
        initComponents();
        controller = new HistoryController(this);
        controller.refreshTable();
        
        
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public JTable getTable_history() {
        return historyList;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        historyList = new javax.swing.JTable();
        button_deleteBuy = new javax.swing.JButton();

        historyList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Comprador", "Teléfono", "Coste"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        historyList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyListMouseClicked(evt);
            }
        });
        historyList.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                historyListPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(historyList);

        button_deleteBuy.setText("Borrar factura");
        button_deleteBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteBuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(button_deleteBuy)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_deleteBuy)
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void historyListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyListMouseClicked
        //controller.writeSelectedRow();
    }//GEN-LAST:event_historyListMouseClicked

    private void historyListPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_historyListPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_historyListPropertyChange

    private void button_deleteBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteBuyActionPerformed
       
        if(getTable_history().getSelectedRowCount()!=1){   
            JOptionPane.showMessageDialog(this,
                "Seleccione una factura.");     
        }else{
            controller.deleteItem();
            JOptionPane.showMessageDialog(this, "Factura borrada.");
        }
        
    }//GEN-LAST:event_button_deleteBuyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_deleteBuy;
    private javax.swing.JTable historyList;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
