/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ProductsController;
import Main.FrameMain;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author alvar
 */
public class PanelProducts extends javax.swing.JPanel {
    
        private FrameMain frame;
        private ProductsController controller;

    /**
     * Creates new form Productos
     */
    public PanelProducts(FrameMain frame) {
        this.frame=frame;
        initComponents();
        controller = new ProductsController(this);
        controller.refreshTable();
    }

    public JTable getProductsList() {
        return ProductsList;
    }
        public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ProductsList = new javax.swing.JTable();
        button_addProduct = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setText("Productos");

        ProductsList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ProductsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductsListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ProductsList);

        button_addProduct.setText("Añadir Producto");
        button_addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductAction(evt);
            }
        });

        jButton2.setText("Editar Producto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProductAction(evt);
            }
        });

        jButton3.setText("Borrar Producto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductAction(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(210, 210, 210))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(button_addProduct)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_addProduct)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(0, 97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ProductsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductsListMouseClicked
        
    }//GEN-LAST:event_ProductsListMouseClicked

    private void addProductAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductAction
        // TODO add your handling code here:
    }//GEN-LAST:event_addProductAction

    private void editProductAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProductAction
        // TODO add your handling code here:
    }//GEN-LAST:event_editProductAction

    private void deleteProductAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductAction
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteProductAction


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ProductsList;
    private javax.swing.JButton button_addProduct;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables


}
