package Main;

import View.AltaClientes;
import View.BajaClientes;
import View.EditClientes;

/**
 *
 * @author alvar
 */
public class FrameMain extends javax.swing.JFrame {

    /**
     * Creates new form EfFrame
     */
    public FrameMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Clientes = new javax.swing.JMenu();
        AltaClientes = new javax.swing.JMenuItem();
        BajaClientes = new javax.swing.JMenuItem();
        EditClientes = new javax.swing.JMenuItem();
        Empleados = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelContenedor.setPreferredSize(new java.awt.Dimension(600, 600));
        PanelContenedor.setLayout(new java.awt.BorderLayout());
        getContentPane().add(PanelContenedor, java.awt.BorderLayout.CENTER);

        Clientes.setText("Clientes");

        AltaClientes.setText("Alta Clientes");
        AltaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaClientesActionPerformed(evt);
            }
        });
        Clientes.add(AltaClientes);

        BajaClientes.setText("Baja Clientes");
        BajaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajaClientesActionPerformed(evt);
            }
        });
        Clientes.add(BajaClientes);

        EditClientes.setText("Editar Clientes");
        EditClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditClientesActionPerformed(evt);
            }
        });
        Clientes.add(EditClientes);

        jMenuBar1.add(Clientes);

        Empleados.setText("Empleados");
        jMenuBar1.add(Empleados);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AltaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaClientesActionPerformed
        PanelContenedor.removeAll();
        AltaClientes altaClientes = new AltaClientes(this);
        PanelContenedor.add(altaClientes, java.awt.BorderLayout.CENTER);
        pack();
    }//GEN-LAST:event_AltaClientesActionPerformed

    private void BajaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajaClientesActionPerformed
        PanelContenedor.removeAll();
        BajaClientes bajaClientes = new BajaClientes(this);
        PanelContenedor.add(bajaClientes, java.awt.BorderLayout.CENTER);
        pack();
    }//GEN-LAST:event_BajaClientesActionPerformed

    private void EditClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditClientesActionPerformed
        PanelContenedor.removeAll();
        EditClientes editclientes = new EditClientes(this);
        PanelContenedor.add(editclientes, java.awt.BorderLayout.CENTER);
        pack();
    }//GEN-LAST:event_EditClientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AltaClientes;
    private javax.swing.JMenuItem BajaClientes;
    private javax.swing.JMenu Clientes;
    private javax.swing.JMenuItem EditClientes;
    private javax.swing.JMenu Empleados;
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
