package Main;

import View.PanelClients;
import View.PanelHistory;
import View.PanelMainMenu;
import View.PanelNewSell;
import View.PanelProducts;

/**
 *
 * @author alvar
 */
public class FrameMain extends javax.swing.JFrame {
    
    /**
     * Creates new form FrameMain
     */
    public FrameMain() {  
        initComponents();
        PanelMainMenu panelMenu = new PanelMainMenu(this);
        PanelContenedor.add(panelMenu, java.awt.BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelButtons = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        openProducts = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        PanelContenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Clientes = new javax.swing.JMenu();
        EditClientes = new javax.swing.JMenuItem();
        Empleados = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Nueva venta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openNewSellAction(evt);
            }
        });
        panelButtons.add(jButton1);

        jButton2.setText("Historial de ventas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openHistoryAction(evt);
            }
        });
        panelButtons.add(jButton2);

        openProducts.setText("Productos");
        openProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openProductsActionPerformed(evt);
            }
        });
        panelButtons.add(openProducts);

        jButton4.setText("Inicio");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuAction(evt);
            }
        });
        panelButtons.add(jButton4);

        getContentPane().add(panelButtons, java.awt.BorderLayout.PAGE_END);

        PanelContenedor.setPreferredSize(new java.awt.Dimension(600, 600));
        PanelContenedor.setLayout(new java.awt.BorderLayout());
        getContentPane().add(PanelContenedor, java.awt.BorderLayout.CENTER);

        Clientes.setText("Clientes");

        EditClientes.setText("Área Clientes");
        EditClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditClientesActionPerformed(evt);
            }
        });
        Clientes.add(EditClientes);

        jMenuBar1.add(Clientes);

        Empleados.setText("Empleados");
        jMenuBar1.add(Empleados);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditClientesActionPerformed
        PanelContenedor.removeAll();
        PanelClients editclientes = new PanelClients(this);
        PanelContenedor.add(editclientes, java.awt.BorderLayout.CENTER);
        pack();
    }//GEN-LAST:event_EditClientesActionPerformed

    private void backToMenuAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuAction
        PanelContenedor.removeAll();
        PanelMainMenu menuPanel = new PanelMainMenu(this);
        PanelContenedor.add(menuPanel, java.awt.BorderLayout.CENTER);
        pack();
    }//GEN-LAST:event_backToMenuAction

    private void openProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openProductsActionPerformed
        PanelContenedor.removeAll();
        PanelProducts productsPanel = new PanelProducts(this);
        PanelContenedor.add(productsPanel, java.awt.BorderLayout.CENTER);
        pack();
    }//GEN-LAST:event_openProductsActionPerformed

    private void openHistoryAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openHistoryAction
        PanelContenedor.removeAll();
        PanelHistory historyPanel = new PanelHistory(this);
        PanelContenedor.add(historyPanel, java.awt.BorderLayout.CENTER);
        pack();
    }//GEN-LAST:event_openHistoryAction

    private void openNewSellAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openNewSellAction
        PanelContenedor.removeAll();
        PanelNewSell newSellPanel = new PanelNewSell(this);
        PanelContenedor.add(newSellPanel, java.awt.BorderLayout.CENTER);
        pack();
    }//GEN-LAST:event_openNewSellAction


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Clientes;
    private javax.swing.JMenuItem EditClientes;
    private javax.swing.JMenu Empleados;
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton openProducts;
    private javax.swing.JPanel panelButtons;
    // End of variables declaration//GEN-END:variables
}
